#!/bin/bash

. bin/loadall

# Adicionando PPAs
Message "Adicionando PPAs"
Install "wget curl"
. bin/system-config/repositories

Message "Atualizando sistema"
Update

Message "Instalando pacotes essenciais"
Install "vlc steam transmission build-essential ubuntu-restricted-extras libdvd-pkg libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext p7zip p7zip-full p7zip-rar lzma lzma-dev software-properties-common jhead jpegoptim libjpeg-turbo-progs optipng"
Spotify
PopCorn
Chrome
Slack
Teamviewer

Message "Instalando pacotes desenvolvimento"
Node
Yarn
VSCode
Teamviewer
Install "terminator git oracle-java8-installer"

Message "Instalando de pacotes globais do Node"
npm i -g react-native-cli browsersync sass

Message "Copiando arquivos de sistema"
SystemFiles